In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
final_cleaned_df=pd.read_csv(r"D:\Data Analyst\EXCEL\supplychain\cleaned\final_cleaned.csv")

In [4]:
eda_data=final_cleaned_df.copy()

# Structure of the Notebook

1. Introduction
2. Dataset Overview
3. Univariate Analysis
4. Bivariate Analysis
5. Multivariate Analysis
6. Time Series Analysis
7. Supply Chain Analysis
8. Customer Analysis
9. Product Analysis
10. Inventory Analysis
11. Shipping Analysis
12. Profitability Analysis
13. Summary of Insights

### Remove unwanted columns for EDA

In [5]:
eda_data.columns

Index(['Unnamed: 0', 'order_line_id', 'order_id', 'date_id', 'order_date',
       'customer_id', 'product_id', 'category', 'seller_id', 'seller_rating',
       'location_id_x', 'delivery_person_id', 'payment_id', 'campaign_id',
       'fulfillment_id', 'quantity', 'unit_price', 'discount_percentage',
       'tax_percentage', 'shipping_fee', 'expected_delivery_date',
       'actual_delivery_date', 'delivery_rating', 'order_status',
       'return_flag', 'refund_amount', 'return_date', 'customer_rating',
       'review_text', 'sentiment_score', 'delivery_delay_days',
       'delivery_sla_days', 'gross_amount', 'discount_amount', 'tax_amount',
       'net_amount', 'product_name', 'brand', 'first_name', 'email_x',
       'phone_number_x', 'marital_status', 'payment_method',
       'payment_provider', 'description', 'seller_name', 'email_y',
       'phone_number_y', 'join_date', 'location_id_y', 'rating',
       'category_focus', 'bank_name', 'bank_account_number', 'ifsc_code',
       'delivery_person_name', 'phone_number', 'employment_type',
       'vehicle_type', 'location_id', 'state', 'city', 'postal_code', 'region',
       'latitude', 'longitude', 'area_type', 'location_category'],
      dtype='object')

In [32]:
df2=eda_data[['order_line_id','order_date', 'category', 'seller_rating','quantity', 'unit_price', 'discount_percentage', 'tax_percentage', 'shipping_fee', 'expected_delivery_date', 'actual_delivery_date', 'delivery_rating', 'order_status', 'return_flag', 'refund_amount', 'return_date', 'customer_rating', 'review_text', 'sentiment_score', 'delivery_delay_days', 'delivery_sla_days', 'gross_amount', 'discount_amount', 'tax_amount', 'net_amount', 'product_name', 'brand', 'first_name', 'marital_status', 'payment_method', 'payment_provider', 'seller_name', 'delivery_person_name', 'employment_type', 'vehicle_type', 'state', 'city', 'postal_code', 'region']]

### Data overview


- Shape	Number of rows and columns
- Columns	Available fields
- Head	Sample records
- Info	Data types and null values
- Describe	Numeric summary
- Duplicates	Duplicate records
- Missing Values	Null counts
- Unique Values	Category counts

In [33]:
df2.shape

(790732, 39)

In [34]:
df2.head()

,order_line_id,order_date,category,seller_rating,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,expected_delivery_date,...,payment_method,payment_provider,seller_name,delivery_person_name,employment_type,vehicle_type,state,city,postal_code,region
0,OL00000001,2026-02-20,Baby,4.6,2,19999,9.66,5.0,86.64,2026-02-22,...,Debit Card,Mastercard,"Virk, Kamdar and Kakar",Bhamini Acharya,Full-Time,Van,Karnataka,Bengaluru,843810,South
1,OL00000002,2025-12-02,Clothing,4.0,4,2499,7.04,5.0,215.79,2025-12-03,...,Debit Card,Visa,"Chauhan, Bahl and Sem",Emir Roy,Contract,Bike,Madhya Pradesh,Bhopal,406047,Central
2,OL00000003,2025-04-03,Gaming,3.9,5,89999,5.75,5.0,86.64,2025-04-05,...,UPI,Paytm,Loke-Gupta,Akarsh Bala,Full-Time,EV Bike,Delhi,Dwarka,246344,North
3,OL00000004,2025-06-01,Home,4.0,3,1499,0.61,5.0,86.64,2025-06-03,...,Debit Card,Visa,Sengupta-D’Alia,Urvi Sabharwal,Contract,Scooter,West Bengal,Kharagpur,705775,East
4,OL00000005,2025-10-25,Pets,4.5,2,299,4.41,5.0,215.79,2025-10-26,...,Wallet,Amazon Pay,Varghese Group,Vivaan Warrior,Full-Time,EV Bike,Haryana,Faridabad,744789,North

In [35]:
df2.describe()

,seller_rating,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,delivery_rating,refund_amount,customer_rating,sentiment_score,delivery_delay_days,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount,postal_code
count,790732.000000,790732.000000,7.907320e+05,790732.000000,790732.0,790732.000000,790732.000000,790732.000000,790732.000000,790732.000000,790732.000000,790732.000000,7.907320e+05,790732.000000,790732.000000,7.907320e+05,790732.000000
mean,3.933004,3.001877,1.443109e+04,4.998254,5.0,116.332926,3.999889,-15.148007,3.717985,0.379188,0.450298,2.663600,4.322148e+04,2156.610857,2161.074214,4.334228e+04,525987.900046
std,0.888860,1.413882,5.030919e+04,2.886348,0.0,72.308419,0.835484,47.047367,0.887309,0.455638,0.668581,1.698761,1.670267e+05,9589.267398,8351.335561,1.672835e+05,259082.111332
min,1.000000,1.000000,2.000000e+01,0.000000,5.0,46.270000,1.000000,-215.790000,1.000000,-1.000000,0.000000,1.000000,2.000000e+01,0.000000,1.000000,6.536000e+01,113106.000000
25%,3.700000,2.000000,6.990000e+02,2.500000,5.0,46.270000,3.700000,0.000000,3.300000,0.180000,0.000000,1.000000,1.598000e+03,56.780100,79.900000,1.743270e+03,273826.000000
50%,4.100000,3.000000,1.999000e+03,4.990000,5.0,86.640000,4.200000,0.000000,3.800000,0.450000,0.000000,2.000000,5.397000e+03,220.310400,269.850000,5.480865e+03,522344.000000
75%,4.500000,4.000000,8.499000e+03,7.500000,5.0,215.790000,4.600000,0.000000,4.400000,0.730000,1.000000,5.000000,2.249500e+04,974.610000,1124.750000,2.240403e+04,755367.000000
max,5.000000,5.000000,1.150000e+06,10.000000,5.0,215.790000,5.000000,0.000000,5.000000,1.000000,2.000000,5.000000,5.750000e+06,572700.000000,287500.000000,6.031796e+06,989497.000000

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790732 entries, 0 to 790731
Data columns (total 39 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   order_line_id           790732 non-null  object
 1   order_date              790732 non-null  object
 2   category                790732 non-null  object
 3   seller_rating           790732 non-null  float64
 4   quantity                790732 non-null  int64
 5   unit_price              790732 non-null  int64
 6   discount_percentage     790732 non-null  float64
 7   tax_percentage          790732 non-null  float64
 8   shipping_fee            790732 non-null  float64
 9   expected_delivery_date  790732 non-null  object
 10  actual_delivery_date    790732 non-null  object
 11  delivery_rating         790732 non-null  float64
 12  order_status            790732 non-null  object
 13  return_flag             790732 non-null  bool
 14  refund_amount           790732 non-null  float64
 15  return_date             103035 non-null  object
 16  customer_rating         790732 non-null  float64
 17  review_text             790732 non-null  object
 18  sentiment_score         790732 non-null  float64
 19  delivery_delay_days     790732 non-null  int64
 20  delivery_sla_days       790732 non-null  int64
 21  gross_amount            790732 non-null  int64
 22  discount_amount         790732 non-null  float64
 23  tax_amount              790732 non-null  float64
 24  net_amount              790732 non-null  float64
 25  product_name            790732 non-null  object
 26  brand                   790732 non-null  object
 27  first_name              790732 non-null  object
 28  marital_status          790732 non-null  object
 29  payment_method          790732 non-null  object
 30  payment_provider        790732 non-null  object
 31  seller_name             790732 non-null  object
 32  delivery_person_name    790732 non-null  object
 33  employment_type         790732 non-null  object
 34  vehicle_type            790732 non-null  object
 35  state                   790732 non-null  object
 36  city                    790732 non-null  object
 37  postal_code             790732 non-null  int64
 38  region                  790732 non-null  object
dtypes: bool(1), float64(11), int64(6), object(21)
memory usage: 230.0+ MB

In [37]:
df2.columns

Index(['order_line_id', 'order_date', 'category', 'seller_rating', 'quantity',
       'unit_price', 'discount_percentage', 'tax_percentage', 'shipping_fee',
       'expected_delivery_date', 'actual_delivery_date', 'delivery_rating',
       'order_status', 'return_flag', 'refund_amount', 'return_date',
       'customer_rating', 'review_text', 'sentiment_score',
       'delivery_delay_days', 'delivery_sla_days', 'gross_amount',
       'discount_amount', 'tax_amount', 'net_amount', 'product_name', 'brand',
       'first_name', 'marital_status', 'payment_method', 'payment_provider',
       'seller_name', 'delivery_person_name', 'employment_type',
       'vehicle_type', 'state', 'city', 'postal_code', 'region'],
      dtype='object')

# Business Question