In [25]:
import pandas as pd
import numpy as np
from scipy import stats

In [26]:
final_cleaned_df=pd.read_csv(r"D:\Data Analyst\EXCEL\supplychain\cleaned\final_cleaned.csv")

In [27]:
final_cleaned_df.head()

,Unnamed: 0,order_line_id,order_id,date_id,order_date,customer_id,product_id,category,seller_id,seller_rating,...,vehicle_type,location_id,state,city,postal_code,region,latitude,longitude,area_type,location_category
0,0,OL00000001,ORD0210788,2026-02-20,2026-02-20,CUST009513,PROD000763,Baby,SELL2379,4.6,...,Van,LOC0010,Karnataka,Bengaluru,843810,South,28.180254,81.284503,Urban,Tier-1
1,1,OL00000002,ORD0248321,2025-12-02,2025-12-02,CUST003412,PROD000142,Clothing,SELL2964,4.0,...,Bike,LOC0053,Madhya Pradesh,Bhopal,406047,Central,35.497063,72.654328,Urban,Tier-2
2,2,OL00000003,ORD0377603,2025-04-03,2025-04-03,CUST065509,PROD001194,Gaming,SELL2485,3.9,...,EV Bike,LOC0095,Delhi,Dwarka,246344,North,25.275521,85.038029,Semi-Urban,Tier-3
3,3,OL00000004,ORD0019414,2025-06-01,2025-06-01,CUST070677,PROD000221,Home,SELL4121,4.0,...,Scooter,LOC0038,West Bengal,Kharagpur,705775,East,30.623518,75.246045,Semi-Urban,Tier-3
4,4,OL00000005,ORD0157859,2025-10-25,2025-10-25,CUST017845,PROD000806,Pets,SELL3183,4.5,...,EV Bike,LOC0109,Haryana,Faridabad,744789,North,33.810392,94.318552,Semi-Urban,Tier-3

In [28]:
df=final_cleaned_df.copy()

In [29]:
df.describe()

,Unnamed: 0,seller_rating,quantity,unit_price,discount_percentage,tax_percentage,shipping_fee,delivery_rating,refund_amount,customer_rating,...,delivery_sla_days,gross_amount,discount_amount,tax_amount,net_amount,rating,bank_account_number,postal_code,latitude,longitude
count,790732.000000,790732.000000,790732.000000,7.907320e+05,790732.000000,790732.0,790732.000000,790732.000000,790732.000000,790732.000000,...,790732.000000,7.907320e+05,790732.000000,790732.000000,7.907320e+05,790732.000000,7.907320e+05,790732.000000,790732.000000,790732.000000
mean,395365.500000,3.933004,3.001877,1.443109e+04,4.998254,5.0,116.332926,3.999889,-15.148007,3.717985,...,2.663600,4.322148e+04,2156.610857,2161.074214,4.334228e+04,2.997974,1.093570e+13,525987.900046,23.408025,82.516359
std,228264.810866,0.888860,1.413882,5.030919e+04,2.886348,0.0,72.308419,0.835484,47.047367,0.887309,...,1.698761,1.670267e+05,9589.267398,8351.335561,1.672835e+05,1.146369,2.316603e+13,259082.111332,8.838560,8.418280
min,0.000000,1.000000,1.000000,2.000000e+01,0.000000,5.0,46.270000,1.000000,-215.790000,1.000000,...,1.000000,2.000000e+01,0.000000,1.000000,6.536000e+01,1.000000,2.649310e+06,113106.000000,8.315545,68.114790
25%,197682.750000,3.700000,2.000000,6.990000e+02,2.500000,5.0,46.270000,3.700000,0.000000,3.300000,...,1.000000,1.598000e+03,56.780100,79.900000,1.743270e+03,2.000000,2.598250e+10,273826.000000,16.243871,75.081435
50%,395365.500000,4.100000,3.000000,1.999000e+03,4.990000,5.0,86.640000,4.200000,0.000000,3.800000,...,2.000000,5.397000e+03,220.310400,269.850000,5.480865e+03,3.000000,4.581740e+11,522344.000000,22.491280,81.362531
75%,593048.250000,4.500000,4.000000,8.499000e+03,7.500000,5.0,215.790000,4.600000,0.000000,4.400000,...,5.000000,2.249500e+04,974.610000,1124.750000,2.240403e+04,4.000000,6.534460e+12,755367.000000,31.658707,90.049016
max,790731.000000,5.000000,5.000000,1.150000e+06,10.000000,5.0,215.790000,5.000000,0.000000,5.000000,...,5.000000,5.750000e+06,572700.000000,287500.000000,6.031796e+06,5.000000,9.972600e+13,989497.000000,36.631323,96.914646

In [30]:
df.mean(numeric_only=True)

Unnamed: 0             3.953655e+05
seller_rating          3.933004e+00
quantity               3.001877e+00
unit_price             1.443109e+04
discount_percentage    4.998254e+00
tax_percentage         5.000000e+00
shipping_fee           1.163329e+02
delivery_rating        3.999889e+00
return_flag            1.303033e-01
refund_amount         -1.514801e+01
customer_rating        3.717985e+00
sentiment_score        3.791877e-01
delivery_delay_days    4.502980e-01
delivery_sla_days      2.663600e+00
gross_amount           4.322148e+04
discount_amount        2.156611e+03
tax_amount             2.161074e+03
net_amount             4.334228e+04
rating                 2.997974e+00
bank_account_number    1.093570e+13
postal_code            5.259879e+05
latitude               2.340803e+01
longitude              8.251636e+01
dtype: float64

In [31]:
df.median(numeric_only=True)

Unnamed: 0             3.953655e+05
seller_rating          4.100000e+00
quantity               3.000000e+00
unit_price             1.999000e+03
discount_percentage    4.990000e+00
tax_percentage         5.000000e+00
shipping_fee           8.664000e+01
delivery_rating        4.200000e+00
return_flag            0.000000e+00
refund_amount          0.000000e+00
customer_rating        3.800000e+00
sentiment_score        4.500000e-01
delivery_delay_days    0.000000e+00
delivery_sla_days      2.000000e+00
gross_amount           5.397000e+03
discount_amount        2.203104e+02
tax_amount             2.698500e+02
net_amount             5.480865e+03
rating                 3.000000e+00
bank_account_number    4.581740e+11
postal_code            5.223440e+05
latitude               2.249128e+01
longitude              8.136253e+01
dtype: float64

In [32]:
df.std(numeric_only=True)

Unnamed: 0             2.282648e+05
seller_rating          8.888597e-01
quantity               1.413882e+00
unit_price             5.030919e+04
discount_percentage    2.886348e+00
tax_percentage         0.000000e+00
shipping_fee           7.230842e+01
delivery_rating        8.354845e-01
return_flag            3.366371e-01
refund_amount          4.704737e+01
customer_rating        8.873091e-01
sentiment_score        4.556381e-01
delivery_delay_days    6.685814e-01
delivery_sla_days      1.698761e+00
gross_amount           1.670267e+05
discount_amount        9.589267e+03
tax_amount             8.351336e+03
net_amount             1.672835e+05
rating                 1.146369e+00
bank_account_number    2.316603e+13
postal_code            2.590821e+05
latitude               8.838560e+00
longitude              8.418280e+00
dtype: float64

In [33]:
df.var(numeric_only=True)

Unnamed: 0             5.210482e+10
seller_rating          7.900716e-01
quantity               1.999063e+00
unit_price             2.531015e+09
discount_percentage    8.331005e+00
tax_percentage         0.000000e+00
shipping_fee           5.228507e+03
delivery_rating        6.980343e-01
return_flag            1.133245e-01
refund_amount          2.213455e+03
customer_rating        7.873174e-01
sentiment_score        2.076060e-01
delivery_delay_days    4.470011e-01
delivery_sla_days      2.885789e+00
gross_amount           2.789792e+10
discount_amount        9.195405e+07
tax_amount             6.974481e+07
net_amount             2.798377e+10
rating                 1.314162e+00
bank_account_number    5.366649e+26
postal_code            6.712354e+10
latitude               7.812014e+01
longitude              7.086745e+01
dtype: float64

### Do late deliveries receive lower customer ratings than on-time deliveries?

### Null Hypothesis (H₀)

- The average customer rating is the same for late and on-time deliveries.

- Alternative Hypothesis (H₁)

- The average customer rating is different for late and on-time deliveries.

In [51]:
import numpy as np

df['delivery_status'] = np.where(
    df['delivery_delay_days'] > 0,
    'late',
    'on_time'
)

In [52]:
df[['delivery_delay_days','delivery_status']]

        delivery_delay_days delivery_status
0                         0         on_time
1                         1            late
2                         1            late
3                         0         on_time
4                         0         on_time
...                     ...             ...
790727                    0         on_time
790728                    1            late
790729                    0         on_time
790730                    0         on_time
790731                    2            late

[790732 rows x 2 columns]

In [53]:
alpha = 0.05

In [58]:
late = df[df["delivery_status"] == "late"]["customer_rating"]

on_time = df[df["delivery_status"] == "on_time"]["customer_rating"]

In [59]:
late

1         4.3
2         4.6
7         2.5
15        1.7
18        1.5
         ...
790720    1.7
790721    4.9
790723    3.5
790728    3.8
790731    2.8
Name: customer_rating, Length: 277201, dtype: float64

In [60]:
from scipy.stats import ttest_ind
t_stat, p_value = ttest_ind(late, on_time)

In [61]:
print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: -0.7100513869419621
P-value: 0.47767248005330776

In [62]:
alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis")
else:
    print("Fail to Reject the Null Hypothesis")

Fail to Reject the Null Hypothesis

In [63]:
from scipy.stats import f_oneway

groups = [
    group['net_amount'].values
    for _, group in df.groupby('category')
]

f_stat, p_value = f_oneway(*groups)

print(f"F-statistic: {f_stat:.4f}")
print(f"P-value: {p_value:.4f}")

F-statistic: 6646.4158
P-value: 0.0000

In [64]:
alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis")
    print("Average revenue differs across product categories.")
else:
    print("Fail to Reject the Null Hypothesis")
    print("No significant difference in average revenue across categories.")

Reject the Null Hypothesis
Average revenue differs across product categories.